name: send_money_app
description: "Easy Send - A Flutter money transfer application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  
  # Dependency Injection
  get_it: ^8.0.3
  
  # Network
  dio: ^5.8.0+1
  
  # Local Storage
  shared_preferences: ^2.5.3
  
  # Functional Programming
  dartz: ^0.10.1
  
  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mockito: ^5.4.6
  build_runner: ^2.5.4
  bloc_test: ^10.0.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
